-- Curated dataset of common grocery abbreviations for token alias suggestions.
INSERT INTO abbreviation_suggestions (word, suggestion)
VALUES
  ('chicken', 'chk'),
  ('chicken', 'chkn'),
  ('chicken', 'chik'),
  ('chicken breast', 'chk brst'),
  ('chicken breast', 'chkn brst'),
  ('chicken thighs', 'chk thgh'),
  ('chicken thighs', 'chkn thgh'),
  ('chicken tenders', 'chk tndr'),
  ('chicken tenders', 'chkn tndr'),
  ('chicken wings', 'chk wng'),
  ('chicken wings', 'chkn wng'),
  ('chicken sausage', 'chk saus'),
  ('chicken sausage', 'chkn saus'),
  ('turkey', 'turk'),
  ('turkey', 'trky'),
  ('turkey', 'trkyy'),
  ('turkey breast', 'turk brst'),
  ('turkey breast', 'trky brst'),
  ('ground turkey', 'grnd turk'),
  ('ground turkey', 'grnd trky'),
  ('salmon', 'salm'),
  ('salmon', 'saln'),
  ('salmon', 'slmn'),
  ('shrimp', 'shrmp'),
  ('shrimp', 'shrp'),
  ('shrimp', 'shrim'),
  ('sausage', 'saus'),
  ('sausage', 'sasg'),
  ('sausage', 'sausg'),
  ('hamburger', 'hmbrgr'),
  ('hamburger', 'hmbgr'),
  ('hamburger', 'burger'),
  ('ground beef', 'grnd bf'),
  ('ground beef', 'grnd beef'),
  ('beef', 'bf'),
  ('beef', 'beefy'),
  ('beef', 'bef'),
  ('steak', 'stk'),
  ('steak', 'stek'),
  ('steak', 'stak'),
  ('pork', 'prk'),
  ('pork', 'porky'),
  ('pork', 'pok'),
  ('pork chops', 'prk chp'),
  ('pork chops', 'pork chp'),
  ('bacon', 'bacn'),
  ('bacon', 'bcn'),
  ('bacon', 'bakon'),
  ('ham', 'hm'),
  ('ham', 'hamm'),
  ('ham', 'hma'),
  ('tofu', 'tof'),
  ('tofu', 'tofuu'),
  ('tofu', 'tf'),
  ('tempeh', 'tmp'),
  ('tempeh', 'tmph'),
  ('tempeh', 'temp'),
  ('egg', 'eg'),
  ('egg', 'eggz'),
  ('egg', 'eggs'),
  ('eggs', 'eggs'),
  ('eggs', 'eggz'),
  ('eggs', 'egs'),
  ('avocado', 'avo'),
  ('avocado', 'avoc'),
  ('avocado', 'avdo'),
  ('broccoli', 'broc'),
  ('broccoli', 'brocc'),
  ('broccoli', 'brcl'),
  ('strawberry', 'straw'),
  ('strawberry', 'strwbry'),
  ('strawberry', 'strbry'),
  ('blueberry', 'blubry'),
  ('blueberry', 'blueb'),
  ('blueberry', 'blbr'),
  ('raspberry', 'rasp'),
  ('raspberry', 'rspbry'),
  ('raspberry', 'rasbr'),
  ('blackberry', 'blkbry'),
  ('blackberry', 'blkbry'),
  ('blackberry', 'blbr'),
  ('banana', 'bana'),
  ('banana', 'bnna'),
  ('banana', 'bnan'),
  ('apple', 'apl'),
  ('apple', 'appl'),
  ('apple', 'appa'),
  ('pear', 'pr'),
  ('pear', 'pearr'),
  ('pear', 'per'),
  ('orange', 'orng'),
  ('orange', 'org'),
  ('orange', 'ornj'),
  ('grapes', 'grps'),
  ('grapes', 'grape'),
  ('grapes', 'grp'),
  ('lemon', 'lemn'),
  ('lemon', 'lemo'),
  ('lemon', 'lem'),
  ('lime', 'lm'),
  ('lime', 'limee'),
  ('lime', 'lmne'),
  ('tomato', 'tom'),
  ('tomato', 'tmto'),
  ('tomato', 'tmtoe'),
  ('potato', 'pot'),
  ('potato', 'pto'),
  ('potato', 'potto'),
  ('sweet potato', 'swt pto'),
  ('sweet potato', 'swt pot'),
  ('onion', 'onn'),
  ('onion', 'onin'),
  ('onion', 'onio'),
  ('red onion', 'rd onn'),
  ('red onion', 'red on'),
  ('yellow onion', 'ylw onn'),
  ('yellow onion', 'yel on'),
  ('green onion', 'grn onn'),
  ('green onion', 'scalln'),
  ('mushroom', 'mush'),
  ('mushroom', 'mshrm'),
  ('mushroom', 'mshr'),
  ('cucumber', 'cuke'),
  ('cucumber', 'cucmb'),
  ('cucumber', 'ccmb'),
  ('zucchini', 'zuc'),
  ('zucchini', 'zuch'),
  ('zucchini', 'zchn'),
  ('asparagus', 'aspgrs'),
  ('asparagus', 'aspar'),
  ('asparagus', 'aspg'),
  ('jalapeno', 'jlpno'),
  ('jalapeno', 'jalap'),
  ('jalapeno', 'jlpn'),
  ('cilantro', 'clntro'),
  ('cilantro', 'cilan'),
  ('cilantro', 'clntr'),
  ('spinach', 'spnch'),
  ('spinach', 'spin'),
  ('spinach', 'spch'),
  ('lettuce', 'lett'),
  ('lettuce', 'lttc'),
  ('lettuce', 'letc'),
  ('romaine', 'romn'),
  ('romaine', 'romai'),
  ('romaine', 'romn lttc'),
  ('pepper', 'pep'),
  ('pepper', 'pepr'),
  ('pepper', 'pppr'),
  ('bell pepper', 'bl pep'),
  ('bell pepper', 'bell pep'),
  ('celery', 'celry'),
  ('celery', 'celer'),
  ('celery', 'clry'),
  ('cauliflower', 'cauliflwr'),
  ('cauliflower', 'cauli'),
  ('cauliflower', 'cflwr'),
  ('artichoke', 'artchk'),
  ('artichoke', 'artch'),
  ('artichoke', 'archk'),
  ('carrot', 'crrt'),
  ('carrot', 'carrt'),
  ('carrot', 'carot'),
  ('baby carrots', 'bby crrt'),
  ('baby carrots', 'baby crrt'),
  ('cabbage', 'cabbg'),
  ('cabbage', 'cabge'),
  ('cabbage', 'cabb'),
  ('brussels sprouts', 'brs sprt'),
  ('brussels sprouts', 'bruss sprt'),
  ('kale', 'kl'),
  ('kale', 'kalee'),
  ('kale', 'kale'),
  ('arugula', 'arug'),
  ('arugula', 'arugl'),
  ('arugula', 'argl'),
  ('bok choy', 'bk chy'),
  ('bok choy', 'bokchy'),
  ('bok choy', 'bkchy'),
  ('ginger', 'gngr'),
  ('ginger', 'gingr'),
  ('ginger', 'gnjr'),
  ('garlic', 'grlc'),
  ('garlic', 'garlc'),
  ('garlic', 'gar'),
  ('parsley', 'prsly'),
  ('parsley', 'parsly'),
  ('parsley', 'prs'),
  ('basil', 'bsl'),
  ('basil', 'bazl'),
  ('basil', 'bsil'),
  ('mint', 'mnt'),
  ('mint', 'mintt'),
  ('mint', 'mntt'),
  ('thyme', 'thym'),
  ('thyme', 'tym'),
  ('thyme', 'thme'),
  ('oregano', 'oreg'),
  ('oregano', 'orgno'),
  ('oregano', 'orag'),
  ('rosemary', 'rsmry'),
  ('rosemary', 'rosem'),
  ('rosemary', 'rosm'),
  ('potatoes', 'ptos'),
  ('potatoes', 'potts'),
  ('potatoes', 'pots'),
  ('yogurt', 'yog'),
  ('yogurt', 'ygrt'),
  ('yogurt', 'yogt'),
  ('greek yogurt', 'grk ygrt'),
  ('greek yogurt', 'greek yog'),
  ('butter', 'btr'),
  ('butter', 'bttr'),
  ('butter', 'butr'),
  ('mozzarella', 'mozz'),
  ('mozzarella', 'mozrla'),
  ('mozzarella', 'mozar'),
  ('parmesan', 'parm'),
  ('parmesan', 'prmsn'),
  ('parmesan', 'parms'),
  ('cheddar', 'ched'),
  ('cheddar', 'cheddr'),
  ('cheddar', 'cheda'),
  ('provolone', 'prov'),
  ('provolone', 'prvlne'),
  ('provolone', 'provo'),
  ('cream', 'crm'),
  ('cream', 'crem'),
  ('cream', 'crem'),
  ('sour cream', 'sour crm'),
  ('sour cream', 'sr crm'),
  ('cream cheese', 'crm chs'),
  ('cream cheese', 'cream chs'),
  ('cottage cheese', 'ctg chs'),
  ('cottage cheese', 'cott chs'),
  ('milk', 'mlk'),
  ('milk', 'milkx'),
  ('milk', 'mik'),
  ('whole milk', 'whl mlk'),
  ('whole milk', 'whole mlk'),
  ('almond milk', 'almnd mlk'),
  ('almond milk', 'alm mlk'),
  ('oat milk', 'oat mlk'),
  ('oat milk', 'oatmilk'),
  ('soy milk', 'soy mlk'),
  ('soy milk', 'soym'),
  ('half and half', 'hnh'),
  ('half and half', 'half half'),
  ('half and half', 'h&h'),
  ('ice cream', 'ice crm'),
  ('ice cream', 'ic crm'),
  ('whipped cream', 'whp crm'),
  ('whipped cream', 'whip crm'),
  ('sourdough', 'sdgh'),
  ('sourdough', 'srdgh'),
  ('sourdough', 'sourd'),
  ('croissant', 'crssnt'),
  ('croissant', 'crois'),
  ('croissant', 'crossnt'),
  ('ciabatta', 'ciab'),
  ('ciabatta', 'ciabt'),
  ('ciabatta', 'ciaba'),
  ('bagel', 'bgl'),
  ('bagel', 'bagl'),
  ('bagel', 'bagel'),
  ('bread', 'brd'),
  ('bread', 'bred'),
  ('bread', 'bread'),
  ('sandwich bread', 'sndwch brd'),
  ('sandwich bread', 'sand brd'),
  ('brioche', 'brioch'),
  ('brioche', 'broch'),
  ('brioche', 'brsh'),
  ('tortilla', 'tort'),
  ('tortilla', 'tortl'),
  ('tortilla', 'trtla'),
  ('pita', 'pta'),
  ('pita', 'pitaa'),
  ('pita', 'pit'),
  ('english muffin', 'eng muff'),
  ('english muffin', 'engl muff'),
  ('boneless', 'bnls'),
  ('boneless', 'bnless'),
  ('boneless', 'bonls'),
  ('skinless', 'sknls'),
  ('skinless', 'skinls'),
  ('skinless', 'sknless'),
  ('organic', 'org'),
  ('organic', 'orgnc'),
  ('organic', 'organ'),
  ('roasted', 'rstd'),
  ('roasted', 'roastd'),
  ('roasted', 'rost'),
  ('smoked', 'smkd'),
  ('smoked', 'smoke'),
  ('smoked', 'smokd'),
  ('grilled', 'grld'),
  ('grilled', 'grilld'),
  ('grilled', 'gril'),
  ('frozen', 'frzn'),
  ('frozen', 'froz'),
  ('frozen', 'frozn'),
  ('marinated', 'mrntd'),
  ('marinated', 'marntd'),
  ('marinated', 'mrnat'),
  ('seasoned', 'ssnd'),
  ('seasoned', 'seasn'),
  ('seasoned', 'sznd'),
  ('sliced', 'slcd'),
  ('sliced', 'slicd'),
  ('sliced', 'slce'),
  ('diced', 'dcd'),
  ('diced', 'dice'),
  ('diced', 'dicd'),
  ('shredded', 'shrd'),
  ('shredded', 'shrdd'),
  ('shredded', 'shred'),
  ('chopped', 'chpd'),
  ('chopped', 'choppd'),
  ('chopped', 'chop'),
  ('ground', 'grnd'),
  ('ground', 'grd'),
  ('ground', 'grond'),
  ('whole', 'whl'),
  ('whole', 'wholee'),
  ('whole', 'whol'),
  ('fresh', 'frsh'),
  ('fresh', 'fres'),
  ('fresh', 'freh'),
  ('dried', 'drd'),
  ('dried', 'dryd'),
  ('dried', 'dri'),
  ('canned', 'cnnd'),
  ('canned', 'cannd'),
  ('canned', 'cand'),
  ('pickled', 'pkld'),
  ('pickled', 'pickl'),
  ('pickled', 'pikld'),
  ('stuffed', 'stfd'),
  ('stuffed', 'stuffd'),
  ('stuffed', 'stuf'),
  ('large', 'lg'),
  ('large', 'lrg'),
  ('large', 'larg'),
  ('small', 'sm'),
  ('small', 'sml'),
  ('small', 'smll'),
  ('medium', 'med'),
  ('medium', 'mdm'),
  ('medium', 'medi'),
  ('extra', 'xtra'),
  ('extra', 'xtr'),
  ('extra', 'extr'),
  ('mini', 'mn'),
  ('mini', 'mini'),
  ('mini', 'mni'),
  ('regular', 'reg'),
  ('regular', 'rg'),
  ('regular', 'regl'),
  ('family', 'fam'),
  ('family', 'fmly'),
  ('family', 'famly'),
  ('value pack', 'val pk'),
  ('value pack', 'value pk'),
  ('party size', 'prty sz'),
  ('party size', 'party sz'),
  ('chocolate', 'choc'),
  ('chocolate', 'choco'),
  ('chocolate', 'chocl'),
  ('peanut', 'pnut'),
  ('peanut', 'peant'),
  ('peanut', 'pnt'),
  ('almond', 'almnd'),
  ('almond', 'almn'),
  ('almond', 'almd'),
  ('cashew', 'cshw'),
  ('cashew', 'cashe'),
  ('cashew', 'cashw'),
  ('coconut', 'cocnt'),
  ('coconut', 'cocnut'),
  ('coconut', 'coco'),
  ('vanilla', 'vanla'),
  ('vanilla', 'van'),
  ('vanilla', 'vnla'),
  ('cinnamon', 'cinn'),
  ('cinnamon', 'cinmn'),
  ('cinnamon', 'cinam'),
  ('mayonnaise', 'mayo'),
  ('mayonnaise', 'mayon'),
  ('mayonnaise', 'myo'),
  ('ketchup', 'ktchp'),
  ('ketchup', 'ketch'),
  ('ketchup', 'ktcp'),
  ('mustard', 'mstrd'),
  ('mustard', 'mustd'),
  ('mustard', 'mstr'),
  ('vinegar', 'vngr'),
  ('vinegar', 'vineg'),
  ('vinegar', 'vngrr'),
  ('soy sauce', 'soy sc'),
  ('soy sauce', 'soy sauc'),
  ('barbecue sauce', 'bbq sc'),
  ('barbecue sauce', 'barbq sc'),
  ('hot sauce', 'ht sc'),
  ('hot sauce', 'hot sc'),
  ('salsa', 'slsa'),
  ('salsa', 'sals'),
  ('salsa', 'salza'),
  ('spaghetti', 'spghti'),
  ('spaghetti', 'spag'),
  ('spaghetti', 'spgti'),
  ('macaroni', 'mac'),
  ('macaroni', 'macar'),
  ('macaroni', 'mcro'),
  ('penne', 'penn'),
  ('penne', 'pene'),
  ('penne', 'pn'),
  ('rice', 'rc'),
  ('rice', 'ricee'),
  ('rice', 'ris'),
  ('brown rice', 'brn rc'),
  ('brown rice', 'brown rc'),
  ('jasmine rice', 'jas rc'),
  ('jasmine rice', 'jasm rc'),
  ('quinoa', 'qnoa'),
  ('quinoa', 'quino'),
  ('quinoa', 'qna'),
  ('oats', 'ots'),
  ('oats', 'oatss'),
  ('oats', 'oats'),
  ('granola', 'grnla'),
  ('granola', 'granl'),
  ('granola', 'grnola'),
  ('cereal', 'cerl'),
  ('cereal', 'cere'),
  ('cereal', 'crl'),
  ('crackers', 'crkrs'),
  ('crackers', 'crackr'),
  ('crackers', 'crkr'),
  ('chips', 'chps'),
  ('chips', 'chipss'),
  ('chips', 'chp'),
  ('pretzels', 'prtzl'),
  ('pretzels', 'pretzl'),
  ('pretzels', 'prtz'),
  ('cookies', 'ckies'),
  ('cookies', 'cooki'),
  ('cookies', 'ckis'),
  ('flour', 'flr'),
  ('flour', 'flourr'),
  ('flour', 'flou'),
  ('sugar', 'sgr'),
  ('sugar', 'sugarr'),
  ('sugar', 'sugr'),
  ('brown sugar', 'brn sgr'),
  ('brown sugar', 'brown sgr'),
  ('powdered sugar', 'pwd sgr'),
  ('powdered sugar', 'pow sgr'),
  ('salt', 'slt'),
  ('salt', 'saltt'),
  ('salt', 'sal'),
  ('peppercorn', 'ppcrn'),
  ('peppercorn', 'pep crn'),
  ('peppercorn', 'ppcorn'),
  ('olive oil', 'olv oil'),
  ('olive oil', 'olive ol'),
  ('canola oil', 'can oil'),
  ('canola oil', 'canla oil'),
  ('sesame oil', 'ses oil'),
  ('sesame oil', 'sesm oil'),
  ('broth', 'brth'),
  ('broth', 'brothh'),
  ('broth', 'brto'),
  ('stock', 'stck'),
  ('stock', 'stok'),
  ('stock', 'stoc'),
  ('soup', 'sup'),
  ('soup', 'soupx'),
  ('soup', 'sop'),
  ('beans', 'bns'),
  ('beans', 'beanz'),
  ('beans', 'bens'),
  ('black beans', 'blk bns'),
  ('black beans', 'black bns'),
  ('chickpeas', 'chkps'),
  ('chickpeas', 'chickp'),
  ('chickpeas', 'chkp'),
  ('lentils', 'lntl'),
  ('lentils', 'lentl'),
  ('lentils', 'lent'),
  ('pasta sauce', 'psta sc'),
  ('pasta sauce', 'past sc'),
  ('tomato sauce', 'tmto sc'),
  ('tomato sauce', 'tom sc'),
  ('pizza sauce', 'pzza sc'),
  ('pizza sauce', 'pizz sc'),
  ('noodles', 'ndls'),
  ('noodles', 'noodl'),
  ('noodles', 'nodl'),
  ('ramen', 'rmn'),
  ('ramen', 'ramn'),
  ('ramen', 'rame'),
  ('sandwich', 'sndwch'),
  ('sandwich', 'sandw'),
  ('sandwich', 'sndw'),
  ('breakfast', 'brkfst'),
  ('breakfast', 'breakf'),
  ('breakfast', 'brkft'),
  ('barbecue', 'bbq'),
  ('barbecue', 'barbq'),
  ('barbecue', 'bbque'),
  ('coffee', 'cof'),
  ('coffee', 'coffeee'),
  ('coffee', 'cf'),
  ('tea', 'te'),
  ('tea', 'teaa'),
  ('tea', 'tee'),
  ('sparkling water', 'spk wtr'),
  ('sparkling water', 'spark wtr'),
  ('water', 'wtr'),
  ('water', 'waterr'),
  ('water', 'watr'),
  ('juice', 'jc'),
  ('juice', 'juic'),
  ('juice', 'jce'),
  ('orange juice', 'orng jc'),
  ('orange juice', 'oj'),
  ('apple juice', 'apl jc'),
  ('apple juice', 'aj'),
  ('smoothie', 'smthie'),
  ('smoothie', 'smthy'),
  ('smoothie', 'smth'),
  ('protein powder', 'prtn pwdr'),
  ('protein powder', 'prot pwdr'),
  ('protein bar', 'prtn br'),
  ('protein bar', 'prot bar'),
  ('snack bar', 'snk br'),
  ('snack bar', 'snack br'),
  ('trail mix', 'trl mx'),
  ('trail mix', 'trail mx'),
  ('popcorn', 'ppcrn'),
  ('popcorn', 'popcrn'),
  ('popcorn', 'pcorn'),
  ('frozen pizza', 'frzn pzza'),
  ('frozen pizza', 'froz pzza'),
  ('frozen vegetables', 'frzn veg'),
  ('frozen vegetables', 'froz veg'),
  ('frozen fruit', 'frzn frt'),
  ('frozen fruit', 'froz frt'),
  ('ice', 'ic'),
  ('ice', 'icee'),
  ('ice', 'is'),
  ('paper towels', 'pp towl'),
  ('paper towels', 'ppr towl'),
  ('toilet paper', 'tlt ppr'),
  ('toilet paper', 'toil ppr'),
  ('napkins', 'npkn'),
  ('napkins', 'napkns'),
  ('napkins', 'napk'),
  ('trash bags', 'trsh bg'),
  ('trash bags', 'trash bag'),
  ('laundry detergent', 'lndry det'),
  ('laundry detergent', 'laund det'),
  ('dish soap', 'dsh sop'),
  ('dish soap', 'dish sop'),
  ('hand soap', 'hnd sop'),
  ('hand soap', 'hand sop')
ON CONFLICT DO NOTHING;
